# Generated by Django 3.2 on 2022-04-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totoalPrice',
            new_name='totalPrice',
        ),
    ]
